language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t apshuk21/docker-react-static-app -f Dev.Dockerfile .
script:
    docker run -e CI=true apshuk21/docker-react-static-app npm run test -- --coverage